/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BoardRouteImport } from './routes/board'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManageUsersRouteImport } from './routes/manage/users'
import { Route as ManageSkillsRouteImport } from './routes/manage/skills'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageUsersRoute = ManageUsersRouteImport.update({
  id: '/manage/users',
  path: '/manage/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageSkillsRoute = ManageSkillsRouteImport.update({
  id: '/manage/skills',
  path: '/manage/skills',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/dashboard': typeof DashboardRoute
  '/signin': typeof SigninRoute
  '/manage/skills': typeof ManageSkillsRoute
  '/manage/users': typeof ManageUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/dashboard': typeof DashboardRoute
  '/signin': typeof SigninRoute
  '/manage/skills': typeof ManageSkillsRoute
  '/manage/users': typeof ManageUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/dashboard': typeof DashboardRoute
  '/signin': typeof SigninRoute
  '/manage/skills': typeof ManageSkillsRoute
  '/manage/users': typeof ManageUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/board'
    | '/dashboard'
    | '/signin'
    | '/manage/skills'
    | '/manage/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/board'
    | '/dashboard'
    | '/signin'
    | '/manage/skills'
    | '/manage/users'
  id:
    | '__root__'
    | '/'
    | '/board'
    | '/dashboard'
    | '/signin'
    | '/manage/skills'
    | '/manage/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardRoute: typeof BoardRoute
  DashboardRoute: typeof DashboardRoute
  SigninRoute: typeof SigninRoute
  ManageSkillsRoute: typeof ManageSkillsRoute
  ManageUsersRoute: typeof ManageUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/users': {
      id: '/manage/users'
      path: '/manage/users'
      fullPath: '/manage/users'
      preLoaderRoute: typeof ManageUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/skills': {
      id: '/manage/skills'
      path: '/manage/skills'
      fullPath: '/manage/skills'
      preLoaderRoute: typeof ManageSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardRoute: BoardRoute,
  DashboardRoute: DashboardRoute,
  SigninRoute: SigninRoute,
  ManageSkillsRoute: ManageSkillsRoute,
  ManageUsersRoute: ManageUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
